const bcrypt =require('bcrypt')
const {encrypt}=require('../securityMiddleware/crypto')
const cAreaSet={
    Company:{
        name:(req)=>({
            name:encrypt(req.body.name)
        }),
        phone:(req)=>({
            phone:encrypt(req.body.phone)
        }),
        description:(req)=>({
            description:encrypt(req.body.description)
        }),
        logo:(req)=>({
            logo:encrypt(req.body.logo)
        })
    },
    Discount:{
        product:(req)=>({
            product:req.body.product
        }),
        discount:(req)=>({
            discount:req.body.discount
        })
    },
    Product:{
        name:(req)=>({
            name:req.body.name
        }),
        description:(req)=>({
            description:req.body.description
        }),
        image:(req)=>({
            image:req.body.image
        }),
        category:(req)=>({
            category:req.body.category
        }),
        brand:(req)=>({
            brand:req.body.brand
        }),
        price:(req)=>({
            price:req.body.price
        }),
        stock:(req)=>({
            stock:req.body.stock
        }),
        currency:(req)=>({
            currency:req.body.currency
        }),
        itemType:(req)=>({
            itemType:req.body.itemType
        })
    },
    ProductRating:{
        description:(req)=>({
            description:req.body.description
        }),
        rating:(req)=>({
            rating:req.body.rating
        })
    },
    Admin:{
        logo:(req)=>({
            logo:encrypt(req.body.logo)
        }),
        siteName:(req)=>({
            siteName:encrypt(req.body.siteName)
        }),
        address:(req)=>({
            address:encrypt(req.body.address)
        })
    },
    Category:{
        mainCategory:(req)=>({
            mainCategory:req.body.mainCategory
        }),
        name:(req)=>({
            name:req.body.name
        })
    },
    Infolog:{
        role:(req)=>({
            role:encrypt(req.body.role)
        }),
        email:(req)=>({
            email:encrypt(req.body.email)
        }),
        password:async(req)=>({
            password:await bcrypt.hash(req.body.password,10)
        })
    },
    MainCategory:{
        name:(req)=>({
            name:req.body.name
        })
    },
    Address:{
        nick:(req)=>({
            nick:encrypt(req.body.nick)
        }),
        address:(req)=>({
            address:encrypt(req.body.address)
        }),
        city:(req)=>({
            city:encrypt(req.body.city)
        }),
        country:(req)=>({
            country:encrypt(req.body.country)
        }),
        zipCode:(req)=>({
            zipCode:encrypt(req.body.zipCode)
        })
    },
    Basked:{
        product:(req)=>({
            product:req.body.product
        }),
        quantity:(req)=>({
            quantity:req.body.quantity
        })
    },
    User:{
        locale:(req)=>({
            locale:req.body.locale
        }),
        name:(req)=>({
            name:encrypt(req.body.name)
        }),
        surname:(req)=>({
            surname:encrypt(req.body.surname)
        }),
        phoneNumber:(req)=>({
            phoneNumber:encrypt(req.body.phoneNumber)
        }),
        identityNumber:(req)=>({
            identityNumber:encrypt(req.body.identityNumber)
        })
    },
}
module.exports={cAreaSet}