const cAreaSetAdminModel=[
    'Company',
    'Discount',
    'Product',
    'ProductRating',
    'Admin',
    'Category',
    'Infolog',
    'MainCategory',
    'Address',
    'Basked',
    'User'
]
const cAreaSetCompanyModel=[
    'Company',
    'Discount',
    'Product',
    'Infolog'
]
const cAreaSetUserModel=[
    'Address',
    'Basked',
    'User',
    'ProductRating',
    'Infolog'
]
const cAreaSetAdminArea=[
    //Company
    'name',
    'phone',
    'description',
    'logo',
    //Discount
    'product',
    'discount',
    //Product
    'name',
    'description',
    'image',
    'category',
    'brand',
    'price',
    'stock',
    'currency',
    'itemType',
    //ProductRating
    'description',
    'rating',
    //Admin
    'logo',
    'siteName',
    'address',
    //Category
    'mainCategory',
    'name',
    //Infolog
    'role',
    'email',
    'password',
    //MainCategory
    'name',
    //Address
    'nick',
    'address',
    'city',
    'country',
    'zipCode',
    //Basked
    'product',
    'quantity',
    //User
    'locale',
    'name',
    'surname',
    'phoneNumber',
    'identityNumber',
]
const cAreaSetCompanyArea=[
    //Company
    'name',
    'phone',
    'description',
    'logo',
    //Discount
    'product',
    'discount',
    //Product
    'name',
    'description',
    'image',
    'category',
    'brand',
    'price',
    'stock',
    'currency',
    'itemType',
    //Infolog
    'role',
    'email',
    'password',
]
const cAreaSetUserArea=[
    //ProductRating
    'description',
    'rating',
    //Infolog
    'role',
    'email',
    'password',
    //Address
    'nick',
    'address',
    'city',
    'country',
    'zipCode',
    //Basked
    'product',
    'quantity',
    //User
    'locale',
    'name',
    'surname',
    'phoneNumber',
    'identityNumber',
]
module.exports={
    cAreaSetAdminModel,
    cAreaSetCompanyModel,
    cAreaSetUserModel,
    cAreaSetAdminArea,
    cAreaSetCompanyArea,
    cAreaSetUserArea
}
